# Generated by Django 3.1 on 2020-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tres_name', models.CharField(max_length=20, verbose_name='식당 이름')),
                ('tres_type', models.IntegerField(verbose_name='식당 종류')),
                ('tres_addr', models.TextField(verbose_name='식당 주소')),
                ('tres_short_info', models.TextField(verbose_name='간단 소개')),
                ('tres_long_info', models.TextField(verbose_name='상세 소개')),
                ('tres_price', models.IntegerField(verbose_name='가격대')),
                ('tres_image', models.CharField(max_length=20, verbose_name='이미지 경로')),
                ('tlocate_x', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='식당 x좌표')),
                ('tlocate_y', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='식당 y좌표')),
                ('ttag_tout', models.IntegerField(verbose_name='1:T/O가능, 0:불가')),
                ('ttag_solo', models.IntegerField(verbose_name='1:혼밥가능, 0:불가')),
                ('ttag_special', models.IntegerField(verbose_name='1:점심특선있음, 0:없음')),
                ('ttag_free', models.IntegerField(verbose_name='1:자율배식가능, 0:불가')),
                ('tstar_avg', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='리뷰 별점의 평균 = 총 별점')),
                ('trev_cnt', models.IntegerField(verbose_name='총 리뷰수')),
            ],
        ),
    ]
