# Generated by Django 3.1 on 2020-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_auto_20200819_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_table',
            name='tlocate_x',
            field=models.FloatField(verbose_name='식당 x좌표'),
        ),
        migrations.AlterField(
            model_name='test_table',
            name='tlocate_y',
            field=models.FloatField(verbose_name='식당 y좌표'),
        ),
        migrations.AlterField(
            model_name='test_table',
            name='tstar_avg',
            field=models.FloatField(verbose_name='리뷰 별점의 평균 = 총 별점'),
        ),
    ]
