# Generated by Django 3.1 on 2020-08-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0005_auto_20200824_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_table',
        ),
        migrations.AlterField(
            model_name='resinfo',
            name='rev_cnt',
            field=models.IntegerField(default=0, null=True, verbose_name='총 리뷰수'),
        ),
        migrations.AlterField(
            model_name='resinfo',
            name='star_avg',
            field=models.FloatField(default=0, null=True, verbose_name='리뷰 별점의 평균 = 총 별점'),
        ),
        migrations.AlterField(
            model_name='resinfo',
            name='tag_solo',
            field=models.IntegerField(verbose_name='1:1인석제공, 0:불가'),
        ),
    ]
