# Generated by Django 3.1 on 2020-08-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_auto_20200824_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resinfo',
            name='tag_free',
            field=models.IntegerField(null=True, verbose_name='1:자율배식, 0:불가'),
        ),
        migrations.AlterField(
            model_name='resinfo',
            name='tag_solo',
            field=models.IntegerField(null=True, verbose_name='1:1인석제공, 0:불가'),
        ),
        migrations.AlterField(
            model_name='resinfo',
            name='tag_special',
            field=models.IntegerField(null=True, verbose_name='1:점심특선, 0:없음'),
        ),
        migrations.AlterField(
            model_name='resinfo',
            name='tag_tout',
            field=models.IntegerField(null=True, verbose_name='1:TakeOut, 0:불가'),
        ),
    ]
