# Generated by Django 3.1 on 2020-09-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0008_members_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rev_writer',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='작성자'),
        ),
    ]
