# Generated by Django 3.1 on 2020-09-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0009_auto_20200902_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='res_id',
            field=models.IntegerField(max_length=5, verbose_name='가게id'),
        ),
    ]
