# Generated by Django 3.1 on 2020-09-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_auto_20200902_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbs_writer', models.CharField(max_length=20, verbose_name='작성자')),
                ('bbs_title', models.TextField(verbose_name='글 제목')),
                ('bbs_content', models.TextField(verbose_name='글 내용')),
                ('bbs_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('bbs_cnt', models.IntegerField(verbose_name='조회수')),
            ],
        ),
    ]
