# Generated by Django 3.1 on 2020-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_bbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs',
            name='bbs_type',
            field=models.CharField(max_length=10, null=True, verbose_name='게시글종류'),
        ),
        migrations.AlterField(
            model_name='review',
            name='res_id',
            field=models.IntegerField(verbose_name='가게id'),
        ),
    ]
